# configs/workflow_config_fast.yaml
# 快速调试配置

BASE_CONFIG_PATH: workflow_config.yaml

qlib_init:
  provider_uri: ~/.qlib/qlib_data/csi1000
  region: cn

task:
  model:
    kwargs:
      n_estimators: 100
      early_stopping_rounds: 10